@messageId = 01FMFT5PJBVQNWT7CE3M4XVAFC

GET {{baseUrl}}/messages
Content-Type: application/json

###

GET {{baseUrl}}/messages/{{messageId}}
Content-Type: application/json

###

POST {{baseUrl}}/messages
Content-Type: application/json

{
  "content": "Olá tudo bem?"
}

###

PUT {{baseUrl}}/messages/{{messageId}}
Content-Type: application/json

{
  "content": "Olá! tudo bem??"
}

###

DELETE {{baseUrl}}/messages/{{messageId}}
Content-Type: application/json
